# Generated by Django 5.1.4 on 2024-12-24 19:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('status', models.CharField(choices=[('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate')], default='ACTIVATE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(related_name='department_courses', to='admin_app.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_courses', to='admin_app.department'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'xls', 'xlsx', 'csv', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'webp', 'svg', 'mp3', 'wav', 'aac', 'ogg', 'wma', 'flac', 'mp4', 'avi', 'mkv', 'mov', 'wmv', 'flv', 'webm', 'zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'html', 'css', 'js', 'json', 'xml', 'yaml', 'py', 'java', 'cpp', 'c', 'h', 'php', 'sql', 'md', 'epub', 'mobi', 'exe', 'apk', 'iso', 'dmg'])])),
                ('course_id', models.CharField()),
                ('name', models.CharField(editable=False, max_length=255)),
                ('size', models.PositiveIntegerField(editable=False)),
                ('file_type', models.CharField(editable=False, max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default=('PENDING', 'Pending'), max_length=10)),
                ('upload_by', models.ForeignKey(editable=False, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Library File',
            },
        ),
    ]
