# Generated by Django 5.1.4 on 2024-12-31 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='First name must contain letters only.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Last name must contain letters only.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(help_text='Digits only.', validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 9 digits without any letters or special characters.', regex='^\\d{9}$')], verbose_name='phone number'),
        ),
    ]
