# Generated by Django 5.1.4 on 2024-12-24 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Library File', 'verbose_name_plural': 'Library Files'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='course_id',
        ),
        migrations.AddField(
            model_name='file',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='admin_app.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
