# Generated by Django 5.1.4 on 2024-12-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='department',
            field=models.ManyToManyField(limit_choices_to={'status': True}, related_name='instructors', to='admin_app.department'),
        ),
    ]
