# Generated by Django 5.1.4 on 2025-01-20 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_instructor_groups_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrequest',
            options={'verbose_name': 'Account Request', 'verbose_name_plural': 'Account Requests'},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, upload_to='uploaded_files/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'xls', 'xlsx', 'csv', 'ppt', 'pptx', 'eddx', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'webp', 'svg', 'mp3', 'wav', 'aac', 'ogg', 'wma', 'flac', 'mp4', 'avi', 'mkv', 'mov', 'wmv', 'flv', 'webm', 'zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'html', 'css', 'js', 'json', 'xml', 'yaml', 'py', 'java', 'cpp', 'c', 'h', 'php', 'sql', 'md', 'epub', 'mobi', 'exe', 'apk', 'iso', 'dmg'])]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='groups',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': True}, related_name='instructors', to='admin_app.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='First name must contain letters only.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='user_images/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Last name must contain letters only.', regex='^[a-zA-Z\\s]+$')]),
        ),
    ]
