# Generated by Django 5.1.4 on 2025-01-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_accountrequest_options_alter_file_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
