# Generated by Django 5.1.4 on 2024-12-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_course_department_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='admin_app.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(related_name='departments', to='admin_app.course'),
        ),
        migrations.AlterField(
            model_name='file',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='admin_app.course'),
            preserve_default=False,
        ),
    ]
