# Generated by Django 5.1.4 on 2024-12-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_course_department_alter_department_courses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Library Files'},
        ),
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.CharField(editable=False, null=True),
        ),
    ]
