# Generated by Django 5.1.4 on 2024-12-31 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_student_group_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=1, limit_choices_to={'status': True}, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='admin_app.department'),
            preserve_default=False,
        ),
    ]
