# Generated by Django 5.1.4 on 2024-12-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(limit_choices_to={'status': True}, related_name='students', through='admin_app.StudentCourse', to='admin_app.course'),
        ),
    ]
