# Generated by Django 5.1.4 on 2024-12-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_file_options_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
