# Generated by Django 5.1.4 on 2024-12-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_file_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_type',
            new_name='type',
        ),
    ]
