# Generated by Django 5.1.4 on 2025-01-02 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='admin_app.group'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='semester',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(choices=[('STUDY', 'Study'), ('SUSPENDED', 'Suspended'), ('COMPLETED', 'Completed')], default='STUDY', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user__is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='admin_app.student'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='year',
            field=models.PositiveIntegerField(default=2025, editable=False),
        ),
    ]
