# Generated by Django 5.1.4 on 2024-12-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_rename_file_type_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
