# Generated by Django 5.1.4 on 2025-01-03 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_student_group_alter_studentcourse_semester_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='course',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='department',
            new_name='departments',
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_by',
            field=models.ForeignKey(editable=False, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student', 'course')},
        ),
    ]
