# Generated by Django 5.1.4 on 2025-01-05 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_rename_course_instructor_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': True}, related_name='instructors', to='admin_app.course'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='departments',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': True}, related_name='instructors', to='admin_app.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(help_text='Digits only.', unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 9 digits without any letters or special characters.', regex='^\\d{9}$')], verbose_name='phone number'),
        ),
    ]
