# Generated by Django 5.1.4 on 2025-01-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_alter_instructor_courses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('first_name', 'last_name')},
        ),
    ]
