# Generated by Django 5.1.4 on 2024-12-26 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(limit_choices_to={'status': True}, related_name='courses', to='admin_app.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='admin_app.department'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'level', 'department')},
        ),
    ]
